/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrimind_proyecto2_rosibellp.vista;

/**
 *
 * @author carri
 */
public class MenuNutricion extends javax.swing.JFrame {

    /**
     * Creates new form MenuNutricion
     */
    public MenuNutricion() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(249,245,239));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jButtonRegistrarPacientes = new javax.swing.JButton();
        jButtonGestionarPacientes = new javax.swing.JButton();
        jButtonGenerarPlan = new javax.swing.JButton();
        jButtonEvaluNutricional = new javax.swing.JButton();
        jButtonHistorial = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel.setText("NutriMind - Menú Nutrición");

        jButtonRegistrarPacientes.setText("Registrar Pacientes");
        jButtonRegistrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPacientesActionPerformed(evt);
            }
        });

        jButtonGestionarPacientes.setText("Gestionar Pacientes");

        jButtonGenerarPlan.setText("Generar Plan");

        jButtonEvaluNutricional.setText("Evaluación Nutricional");

        jButtonHistorial.setText("Historial Nutricional");

        jButtonCerrar.setText("Cerrar Sesión ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGenerarPlan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonHistorial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRegistrarPacientes)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonGestionarPacientes)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEvaluNutricional)
                            .addComponent(jButtonCerrar))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCerrar, jButtonEvaluNutricional, jButtonGenerarPlan, jButtonGestionarPacientes, jButtonHistorial, jButtonRegistrarPacientes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarPacientes)
                    .addComponent(jButtonGestionarPacientes)
                    .addComponent(jButtonEvaluNutricional))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarPlan)
                    .addComponent(jButtonHistorial)
                    .addComponent(jButtonCerrar))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCerrar, jButtonEvaluNutricional, jButtonGenerarPlan, jButtonGestionarPacientes, jButtonHistorial, jButtonRegistrarPacientes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPacientesActionPerformed
        // TODO add your handling code here:
        new MenuPNRegistrarPacientes().setVisible(true); // abre el menú del Profesional
        this.dispose();                        
    }//GEN-LAST:event_jButtonRegistrarPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNutricion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNutricion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNutricion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNutricion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNutricion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEvaluNutricional;
    private javax.swing.JButton jButtonGenerarPlan;
    private javax.swing.JButton jButtonGestionarPacientes;
    private javax.swing.JButton jButtonHistorial;
    private javax.swing.JButton jButtonRegistrarPacientes;
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables
}
